{% set name = "hhsuite" %}
{% set version = environ["GIT_FULL_HASH"][0:7] %}
{% if "GIT_DESCRIBE_TAG" in environ %}
{%     set version = environ["GIT_DESCRIBE_TAG"] | replace("-", "_") %}
{%     if "GIT_DESCRIBE_NUMBER" in environ and environ["GIT_DESCRIBE_NUMBER"] | int > 0 %}
{%         set version = version ~ "_" ~ environ["GIT_BUILD_STR"] %}
{%     endif %}
{% endif %}
# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/soedinglab/hh-suite.git
    git_rev: master
    patches:
      - makefiles.patch
  - path: env_vars

build:
  number: 1
  string: {{ architecture }}
  features:
  - arch_{{ architecture }}
  script: |
    mkdir build-{{ architecture }}
    cd build-{{ architecture }}
    cmake \
     -DCMAKE_BUILD_TYPE=RelWithDebInfo \
     -G "Unix Makefiles" \
     -DARCH={{ architecture }} \
     -DCMAKE_INSTALL_PREFIX=$PREFIX ..
    make
    make install

    # Make scripts relocatable by replacing hard-coded paths with placeholder
    soeding_prefix=/cluster/toolkit/production/bioprogs
    placehold_prefix=/opt/anaconda1anaconda2anaconda3
    sed -i "s|$soeding_prefix/blast/bin|$placehold_prefix/bin|" "${PREFIX}/scripts/HHPaths.pm"
    sed -i "s|$soeding_prefix/psipred/data|$placehold_prefix/share/psipred/data|" "${PREFIX}/scripts/HHPaths.pm"
    sed -i "s|$soeding_prefix/psipred/bin|$placehold_prefix/bin|" "${PREFIX}/scripts/HHPaths.pm"

    install -d -m755 ${PREFIX}/share/hhsuite
    mv ${PREFIX}/hhsuite-userguide.pdf ${PREFIX}/share/hhsuite
    mv ${PREFIX}/lib64 ${PREFIX}/lib
    mv ${PREFIX}/scripts ${PREFIX}/share/hhsuite/
    mv ${PREFIX}/data ${PREFIX}/share/hhsuite/

    install -m755 -d "$PREFIX/etc/conda/activate.d"
    install -m755 -d "$PREFIX/etc/conda/deactivate.d"
    install -m755 "../activate.d/hhsuite.sh" "$PREFIX/etc/conda/activate.d"
    install -m755 "../deactivate.d/hhsuite.sh" "$PREFIX/etc/conda/deactivate.d"


requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
  host:
    - libgcc-ng
  run:
    - psipred

about:
  home: https://github.com/soedinglab/hh-suite
  license: GPL2
